version: '3.6'

services:
  conectados-middleware:
    build:
      context: middleware
      dockerfile: Dockerfile
    volumes:
    - ./middleware:/usr/middleware
    depends_on:
      - conectados-post
      - conectados-client
    links:
      - conectados-post
      - conectados-client
    command: npm run-script start:prod
    ports:
    - 3000:3000

  conectados-post:
    build:
      context: post-service
      dockerfile: Dockerfile
    volumes:
    - ./post-service:/usr/post
    depends_on:
      - conectados-mongo
    links:
      - conectados-mongo
    command: npm run-script start:prod
    ports:
    - 3001:3001

  conectados-client:
    build:
      context: client-service
      dockerfile: Dockerfile
    volumes:
    - ./client-service:/usr/client
    depends_on:
      - conectados-mongo
    links:
      - conectados-mongo
    command: npm run-script start:prod
    ports:
    - 3002:3002

  conectados-mongo:
    image: mongo:latest
    container_name: conectados-mongo
    logging:
      driver: "none"
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
      - mongoconfig:/data/configdb

volumes:
  mongodb:
  mongoconfig:
