version: '3.6'

services:
  conectados-middleware:
    build:
      context: middleware
      dockerfile: Dockerfile
    volumes:
    - ./middleware:/usr/middleware
    depends_on:
      - conectados-post
    links:
      - conectados-post
    command: npm start
    ports:
    - 3000:3000

  conectados-post:
    build:
      context: post-service
      dockerfile: Dockerfile
    volumes:
    - ./post-service:/usr/post
    command: npm start
    ports:
    - 3001:3001